// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB28Gj0t4hZTeZhwPT7U1l-w9gX6ULRPMg',
    appId: '1:501237192933:web:921e808cf26fcf1b6cdc0c',
    messagingSenderId: '501237192933',
    projectId: 'chat-app-c5a79',
    authDomain: 'chat-app-c5a79.firebaseapp.com',
    storageBucket: 'chat-app-c5a79.appspot.com',
    measurementId: 'G-HP5SZQD17J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Ywh4gEgYdnfqQZRPdW8gkIU5FuT93O0',
    appId: '1:501237192933:android:3bf3a742a72d9a4f6cdc0c',
    messagingSenderId: '501237192933',
    projectId: 'chat-app-c5a79',
    storageBucket: 'chat-app-c5a79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx0CpfHX4g4LhwT2IBSjp7EIGJT7gk7VU',
    appId: '1:501237192933:ios:d3e0bc0ee678845f6cdc0c',
    messagingSenderId: '501237192933',
    projectId: 'chat-app-c5a79',
    storageBucket: 'chat-app-c5a79.appspot.com',
    iosClientId:
        '501237192933-der4uuui10qnhjsjameoehr936ka1d65.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx0CpfHX4g4LhwT2IBSjp7EIGJT7gk7VU',
    appId: '1:501237192933:ios:d3e0bc0ee678845f6cdc0c',
    messagingSenderId: '501237192933',
    projectId: 'chat-app-c5a79',
    storageBucket: 'chat-app-c5a79.appspot.com',
    iosClientId:
        '501237192933-der4uuui10qnhjsjameoehr936ka1d65.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatsApp',
  );
}
